object Versions {
    const val shimmerVersion = "0.5.0"
    const val retrofitVersion = "2.9.0"
    const val coroutinesVersion = "1.6.0"
    const val koinVersion = "3.1.5"
    const val coilVersion = "2.0.0-rc02"
    const val decoroVersion = "1.4.1"
    const val workManagerVersion = "2.7.1"
    const val adapterDelegatesVersion = "4.3.1"
    const val navigationVersion = "2.4.1"
    const val firebaseVersion = "29.0.4"
    const val lottieVersion = "5.0.3"
    const val coreVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val junitVersion = "4.13.2"
    const val androidJunitVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val lifecycleVersion = "2.4.1"
    const val mockkVersion = "1.12.3"
    const val roomVersion = "2.4.2"
    const val orbitMviVersion = "4.3.2"
    const val composeVersion = "1.1.1"
}
